name: "CI/CD"

on:
  - push
  - pull_request

jobs:

  lint:
    name: lint
    uses: wolcomm/.github/.github/workflows/rust-lint.yml@master
    with:
      build-dependencies: "protobuf-compiler"

  test:
    name: test
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
        args:
          - --lib
          - --test versions
        include:
          - toolchain: nightly
            args: --doc
    uses: wolcomm/.github/.github/workflows/rust-test.yml@codecov-token
    with:
      toolchain: ${{ matrix.toolchain }}
      args: ${{ matrix.args }}
      build-dependencies: "protobuf-compiler"
    secrets: inherit

  publish:
    name: publish
    if: ${{ github.event_name == 'push' &&
            startsWith(github.ref, 'refs/tag') }}
    needs:
      - lint
      - test
    uses: wolcomm/.github/.github/workflows/rust-publish.yml@master
    with:
      build-dependencies: "protobuf-compiler"
    secrets: inherit
